modLoader="javafml"
loaderVersion="[4,)"
license="LGPLv3"
issueTrackerURL="https://github.com/nice-john/Creatures_And_Beasts-Forge/issues"

[[mods]]
modId="cnb"
version="${file.jarVersion}"
displayName="Creatures and Beasts: Unofficial Port"
displayURL="https://github.com/CreaturesAndBeasts/Creatures_And_Beasts-Forge"
logoFile="logo.png"
credits="Credits to AzureDoom and Christian for contributions to the code"
authors="Joosh, CGessinger, and HellionGames"
description='''
Creatures and Beasts is a vanilla-style creature mod which fills each biome with new mobs, from the plains of the overworld to the void of the end!
'''

[[dependencies.cnb]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cnb]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cnb]]
    modId = "geckolib"
    type = "required"
    versionRange = "[4.8.3,)"
    ordering = "BEFORE"
    side = "BOTH"
